// JsFromRoutes CacheKey 9bab1a64b6b6390763f26bb806eeed2a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/accept_friend_request_broadcast'),
}
