// JsFromRoutes CacheKey 92efbfca0b0d2ffb92a36383973b3431
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as friendRequests } from './FriendRequestsApi'
export { default as friendships } from './FriendshipsApi'
