// JsFromRoutes CacheKey 99124e69c1e33caa083ae4ee23bbdb22
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/all_users_broadcast'),
}
