// JsFromRoutes CacheKey 0013b806c3ef4e159322ea6f3432562f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/broadcasts'),
}
