// JsFromRoutes CacheKey e593ed5b3a284231e01bc702011a1968
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/cancel_friend_request_broadcast'),
}
