// JsFromRoutes CacheKey 15ed5938947a56b242eae0d9dc329700
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/chats'),
  create: /* #__PURE__ */ definePathHelper('post', '/chats'),
  show: /* #__PURE__ */ definePathHelper('get', '/chats/:id'),
}
