// JsFromRoutes CacheKey bffd6ba87768d9e31adc9539191787b1
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/chats/:id'),
}
