// JsFromRoutes CacheKey 8ff29bc0400f23e9e7a0bebf4ff2b65d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/chats'),
  show: /* #__PURE__ */ definePathHelper('get', '/chats/:id'),
}
