// JsFromRoutes CacheKey 9f2150346861624883efcd12fe7a3498
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/chat_users_broadcast'),
}
