// JsFromRoutes CacheKey 9a559d2433cf319459442ecede7cd07a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/friend_categories'),
}
