// JsFromRoutes CacheKey 36ca745cc368c420f5e23dfff71dc317
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/pending_friends'),
  create: /* #__PURE__ */ definePathHelper('post', '/pending_friends'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/pending_friends/:id'),
}
