// JsFromRoutes CacheKey 1dd3cf069b07f33efbdfb06d850bf3df
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/friends'),
  create: /* #__PURE__ */ definePathHelper('post', '/friends'),
}
