// JsFromRoutes CacheKey 9d6a9caee83252cef0e6e17aae70d0ef
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/friends'),
  create: /* #__PURE__ */ definePathHelper('post', '/friends'),
  new: /* #__PURE__ */ definePathHelper('get', '/friends/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/friends/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/friends/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/friends/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/friends/:id'),
}
