// JsFromRoutes CacheKey c4b91e25db194635a520b622d1c3cb8a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/friend_requests'),
  create: /* #__PURE__ */ definePathHelper('post', '/friend_requests'),
  new: /* #__PURE__ */ definePathHelper('get', '/friend_requests/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/friend_requests/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/friend_requests/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/friend_requests/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/friend_requests/:id'),
}
