// JsFromRoutes CacheKey 58d619c364d829f7faa61ddc376215ee
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/friends'),
  create: /* #__PURE__ */ definePathHelper('post', '/friends'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/friends/:id'),
}
