// JsFromRoutes CacheKey 671ef7a78da4c685b13bda364b043964
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/incoming_friends'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/incoming_friends/:id'),
}
