// JsFromRoutes CacheKey 46fb3e82abecf09838e7fd3409810de4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/incoming_friends'),
}
