// JsFromRoutes CacheKey 76924f9c27eb3c1742d65f7f79f1d990
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/member_lists'),
  create: /* #__PURE__ */ definePathHelper('post', '/member_lists'),
}
