// JsFromRoutes CacheKey 88cc0f613a7d1e3724866ea42fd33bbd
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/messages'),
  create: /* #__PURE__ */ definePathHelper('post', '/messages'),
}
