// JsFromRoutes CacheKey 788626cfbe5ee23f06c05a716f972207
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/outgoing_friends'),
  create: /* #__PURE__ */ definePathHelper('post', '/outgoing_friends'),
}
