// JsFromRoutes CacheKey 63e46aecf3c8ba834fab43a98d2b5ed2
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/outgoing_friends'),
  create: /* #__PURE__ */ definePathHelper('post', '/outgoing_friends'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/outgoing_friends/:id'),
}
