// JsFromRoutes CacheKey cf8f23a92638f1ec93e47896392041c6
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/per_user_all_users_broadcast'),
}
