// JsFromRoutes CacheKey b62bc3fd102b744a8f948e17a84a17c9
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  edit: /* #__PURE__ */ definePathHelper('get', '/profiles/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/profiles/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/profiles/:id'),
}
