// JsFromRoutes CacheKey 7ca4231597f5ea6bbb777865c7f16e21
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/profile_broadcast'),
}
