// JsFromRoutes CacheKey e16956a24303ca991bff7d1572516b3e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/sign_up'),
}
