// JsFromRoutes CacheKey 5769163936ad260b7a526914fe824016
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/sign_up'),
  create: /* #__PURE__ */ definePathHelper('post', '/sign_up'),
}
