// JsFromRoutes CacheKey f616edfa29e4e3388151b0cae49e8e38
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/reject_friend_request_broadcast'),
}
