// JsFromRoutes CacheKey f97d95c6f75bf19c57dd5a5a9810c41c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/send_friend_request_broadcast'),
}
