// JsFromRoutes CacheKey 6a49aad812ae93cafd1570f12906ead4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/send_message_broadcast'),
}
