// JsFromRoutes CacheKey fb3d93ab0bcfe966c865fff7b1ce4eb0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/sessions'),
  show: /* #__PURE__ */ definePathHelper('get', '/sessions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/sessions/:id'),
}
