// JsFromRoutes CacheKey 282b65a3bb72770e6080626e15dfab1e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/sign_in'),
  index: /* #__PURE__ */ definePathHelper('get', '/sessions'),
  show: /* #__PURE__ */ definePathHelper('get', '/sessions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/sessions/:id'),
}
