// JsFromRoutes CacheKey cab1b03bc7ea47866d41f0f14e2631a5
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/sessions'),
  create: /* #__PURE__ */ definePathHelper('post', '/sessions'),
  new: /* #__PURE__ */ definePathHelper('get', '/sessions/new'),
  show: /* #__PURE__ */ definePathHelper('get', '/sessions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/sessions/:id'),
}
