// JsFromRoutes CacheKey 95ce3cc80ab39e2316cde76da42e8f15
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/unfriend_broadcast'),
}
