// JsFromRoutes CacheKey eef9bc3767e5a9a4b196b368df1a511c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/users'),
}
