// JsFromRoutes CacheKey 1ab880daf0e4204e2f648579001bf7dd
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/users_broadcast'),
}
