require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/incoming_friends", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # IncomingFriend. As you add validations to IncomingFriend, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      IncomingFriend.create! valid_attributes
      get incoming_friends_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      incoming_friend = IncomingFriend.create! valid_attributes
      get incoming_friend_url(incoming_friend)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_incoming_friend_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      incoming_friend = IncomingFriend.create! valid_attributes
      get edit_incoming_friend_url(incoming_friend)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new IncomingFriend" do
        expect {
          post incoming_friends_url, params: { incoming_friend: valid_attributes }
        }.to change(IncomingFriend, :count).by(1)
      end

      it "redirects to the created incoming_friend" do
        post incoming_friends_url, params: { incoming_friend: valid_attributes }
        expect(response).to redirect_to(incoming_friend_url(IncomingFriend.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new IncomingFriend" do
        expect {
          post incoming_friends_url, params: { incoming_friend: invalid_attributes }
        }.to change(IncomingFriend, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post incoming_friends_url, params: { incoming_friend: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested incoming_friend" do
        incoming_friend = IncomingFriend.create! valid_attributes
        patch incoming_friend_url(incoming_friend), params: { incoming_friend: new_attributes }
        incoming_friend.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the incoming_friend" do
        incoming_friend = IncomingFriend.create! valid_attributes
        patch incoming_friend_url(incoming_friend), params: { incoming_friend: new_attributes }
        incoming_friend.reload
        expect(response).to redirect_to(incoming_friend_url(incoming_friend))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        incoming_friend = IncomingFriend.create! valid_attributes
        patch incoming_friend_url(incoming_friend), params: { incoming_friend: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested incoming_friend" do
      incoming_friend = IncomingFriend.create! valid_attributes
      expect {
        delete incoming_friend_url(incoming_friend)
      }.to change(IncomingFriend, :count).by(-1)
    end

    it "redirects to the incoming_friends list" do
      incoming_friend = IncomingFriend.create! valid_attributes
      delete incoming_friend_url(incoming_friend)
      expect(response).to redirect_to(incoming_friends_url)
    end
  end
end
