require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/outgoing_friends", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # OutgoingFriend. As you add validations to OutgoingFriend, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OutgoingFriend.create! valid_attributes
      get outgoing_friends_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      outgoing_friend = OutgoingFriend.create! valid_attributes
      get outgoing_friend_url(outgoing_friend)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_outgoing_friend_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      outgoing_friend = OutgoingFriend.create! valid_attributes
      get edit_outgoing_friend_url(outgoing_friend)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OutgoingFriend" do
        expect {
          post outgoing_friends_url, params: { outgoing_friend: valid_attributes }
        }.to change(OutgoingFriend, :count).by(1)
      end

      it "redirects to the created outgoing_friend" do
        post outgoing_friends_url, params: { outgoing_friend: valid_attributes }
        expect(response).to redirect_to(outgoing_friend_url(OutgoingFriend.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OutgoingFriend" do
        expect {
          post outgoing_friends_url, params: { outgoing_friend: invalid_attributes }
        }.to change(OutgoingFriend, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post outgoing_friends_url, params: { outgoing_friend: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested outgoing_friend" do
        outgoing_friend = OutgoingFriend.create! valid_attributes
        patch outgoing_friend_url(outgoing_friend), params: { outgoing_friend: new_attributes }
        outgoing_friend.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the outgoing_friend" do
        outgoing_friend = OutgoingFriend.create! valid_attributes
        patch outgoing_friend_url(outgoing_friend), params: { outgoing_friend: new_attributes }
        outgoing_friend.reload
        expect(response).to redirect_to(outgoing_friend_url(outgoing_friend))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        outgoing_friend = OutgoingFriend.create! valid_attributes
        patch outgoing_friend_url(outgoing_friend), params: { outgoing_friend: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested outgoing_friend" do
      outgoing_friend = OutgoingFriend.create! valid_attributes
      expect {
        delete outgoing_friend_url(outgoing_friend)
      }.to change(OutgoingFriend, :count).by(-1)
    end

    it "redirects to the outgoing_friends list" do
      outgoing_friend = OutgoingFriend.create! valid_attributes
      delete outgoing_friend_url(outgoing_friend)
      expect(response).to redirect_to(outgoing_friends_url)
    end
  end
end
