development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: messaging_app_development

test:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: messaging_app_test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: messaging_app_production
